web:
  build: .
  volumes:
    - ../src/:/var/www/html/
  ports:
    - "9999:80"
  links:
   - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_DATABASE: "ebs"
  volumes:
    - ../init/:/docker-entrypoint-initdb.d/
